### ISSUE TITLE
as a backend dev, I should have a database design that aligns with the functionality of the app, so that I can implement the app

### ISSUE THREAD

**Issue by Nnadozie** [Nnadozie/paw#23]
Resources important for after this task. Please read through all.
- can say diff btwn sql and nosql
- should understand what a database schema is: http://www.databaseanswers.org/tutorial4_db_schema/index.htm  CAN STOP AT SLIDE 5.
- should understand composite keys: https://www.javatpoint.com/sql-composite-key
- should understand normalization: https://mariadb.com/kb/en/library/database-normalization/  CAN STOP AT 3rd Normalization.
- should have a sense of what operations are possible with a sql database: https://www.postgresqltutorial.com/

**Comment by tosinfarai** [comment]
![IMG-20200508-WA0019](https://user-images.githubusercontent.com/53543135/81447023-c6c09d80-9173-11ea-811d-fd1cb992a2c5.jpeg)
![IMG-20200508-WA0020](https://user-images.githubusercontent.com/53543135/81447027-c88a6100-9173-11ea-9372-3ce89865eb06.jpeg)
![IMG-20200508-WA0018](https://user-images.githubusercontent.com/53543135/81447032-c9bb8e00-9173-11ea-90de-a8397d391461.jpeg)

**Comment by tosinfarai** [comment]
Added basic design
